name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      
    # Checkout
    - uses: actions/checkout@v2

    # Ruby setup
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    # Caches
    - name: Carthage cache
      uses: actions/cache@v1
      with:
        path: Examples/swift/Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}-${{ hashFiles('Examples/swift/Carthage/**') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
    - name: SPM cache
      uses: actions/cache@v1
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}-${{ hashFiles('.build/**') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    # Setup
    - name: Setup
      run: |
        sh scripts/setup.sh
    
    # Tests
    - name: Tests
      run: swift test